"""Add comments column to visit table

Revision ID: 52859aa6a421
Revises: eafea8c23af5
Create Date: 2023-04-07 07:41:50.496287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52859aa6a421'
down_revision = 'eafea8c23af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'comments')
    # ### end Alembic commands ###
